### ISSUE TITLE
Functionality - Placing order

### ISSUE THREAD

**Issue by PatrikG-96** [oyuz/E-commerce-site#13]
From user story:
- As a customer, I want to be able to place my order, so that I am able torecieve the pizzas I want

Depends on:
- Initial implementation - None
- Future implementation - Shopping cart functionality

Expected result:
- Inital implementation - a user should be able to order a single item
- Future implementation - a user should be able to place an order on his shopping cart

**Comment by oyuz** [comment]
Complete
